# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Ubuntu 20.04 VM, kernel 5.13 has been loaded with:
  # guest additions included
  # add-apt-repository -y ppa:wireshark-dev/stable
  # add-apt-repository -y ppa:linuxgndu/sqlitebrowser
  # apt update
  # apt install -y git sshpass curl dnsmasq sqlitebrowser wireshark openssh-server iperf3 net-tools
  # usermod -a -G wireshark vagrant
  # sudo pip install matplotlib #so avail for all users
  # echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
  # systemctl restart ssh
  # pip install pycryptodome # for python encryption support in NCO

  # Single machine for running sample modules
  # config.vm.box = "squanchy/layer4.5"
  # config.vm.box_version = "1.1"


  # Multiple machines for running experiment modules
  config.vm.define "server" do |server|
    server.vm.box = "squanchy/layer4.5"
    server.vm.box_version = "1.1"
    server.vm.network "private_network", ip: "10.0.0.20", virtualbox__intnet: "layer", nic_type: "virtio"
    server.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true
      vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
      vb.customize ["bandwidthctl", :id, "add", "VagrantLimit", "--type", "network", "--limit", "1000m"]
      vb.customize ["modifyvm", :id, "--nicbandwidthgroup2", "VagrantLimit"]

    end
  end

  config.vm.define "client" do |client|
    client.vm.box = "squanchy/layer4.5"
    client.vm.box_version = "1.1"
    client.vm.network "private_network", ip: "10.0.0.40", virtualbox__intnet: "layer", nic_type: "virtio"
    client.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true
      vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
      vb.customize ["bandwidthctl", :id, "add", "VagrantLimit", "--type", "network", "--limit", "1000m"]
      vb.customize ["modifyvm", :id, "--nicbandwidthgroup2", "VagrantLimit"]
    end
  end






  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../../software_defined_customization", "/home/vagrant/software_defined_customization"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #   vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  #
  #   # Customize the amount of memory on the VM:
  #   # vb.memory = "4096"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  config.vm.provision :shell, path: "setup.sh"
end
