---
- name: Run Nmap scan from 10.0.8.22
  hosts: 10.0.8.22
  gather_facts: false

  vars:
    subnet: "10.0.2.0/24"
    ports: "80,443"

  tasks:
    - name: Run Nmap scan on the subnet from the target host
      command: "nmap -p {{ ports }} -sT -Pn {{ subnet }}"
      register: nmap_scan_results
      become: true # If Nmap requires sudo

    - name: Print the raw Nmap output
      debug:
        var: nmap_scan_results.stdout_lines
